2021-09-29 05:13:34,738 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-09-29 05:13:34,738 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/hayotbek/.local/lib/python3.8/site-packages/instabot/bot/bot.py
2021-09-29 05:13:34,739 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-09-29 05:14:39,103 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2021-09-29 05:14:39,602 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-09-29 05:14:47,335 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-09-29 05:15:52,939 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2021-09-29 05:16:59,613 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [200]>
2021-09-29 05:16:59,613 - instabot version: 0.117.0 (api) - INFO - Logged-in successfully as 'gafuyr22hayotttt'!
2021-09-29 05:16:59,614 - instabot version: 0.117.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2021-09-29 05:17:31,167 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0b4e81d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2021-09-29 05:17:34,920 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-09-29 05:17:35,326 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: zr/token/result/?device_id=android-8fdc08f14ca8c6e3&token_hash=&custom_device_id=android-8fdc08f14ca8c6e3&fetch_reason=token_expired returned response: <Response [200]>
2021-09-29 05:17:35,777 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: multiple_accounts/get_account_family/ returned response: <Response [200]>
2021-09-29 05:17:36,229 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-09-29 05:18:40,900 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: igtv/browse_feed/?prefetch=1 returned response: <Response [200]>
